/**
 * Refreshes the vendored Devin ACP documentation snapshot under `docs/acp/`.
 *
 * Why a snapshot instead of a live reference: OpenCode references resolve only
 * to a local `path` or a Git `repository`. `docs.devin.ai` is neither, so the
 * load-bearing pages are committed here and refreshed on demand. Every file
 * carries its source URL and fetch date; a snapshot is evidence of what the
 * page said, never proof that it still says it.
 *
 * Usage: bun scripts/fetch-devin-acp-docs.ts [--check]
 *   --check  report drift without writing (exit 1 if a page changed)
 */
import { mkdir } from "node:fs/promises"
import { join } from "node:path"

interface Page {
  readonly file: string
  readonly url: string
  readonly why: string
}

/** The Devin pages this project's wire contract depends on. Add a page here, not a page on disk. */
const PAGES: readonly Page[] = [
  {
    file: "desktop-acp.md",
    url: "https://docs.devin.ai/desktop/acp.md",
    why: "Devin Desktop as an ACP host: launching third-party agents, the local/team registry, and which ACP agents are known-good.",
  },
  {
    file: "desktop-acp-custom.md",
    url: "https://docs.devin.ai/desktop/acp-custom.md",
    why: "Devin Desktop as an ACP host, agent side: the methods an agent must implement and the two places Devin Desktop diverges from the spec (no session modes, no terminal capabilities).",
  },
  {
    file: "cli-acp-zed.md",
    url: "https://docs.devin.ai/cli/acp/zed.md",
    why: "`devin acp` driven by Zed's Agent Panel — a worked example of a third-party ACP client against the exact subprocess we spawn.",
  },
  {
    file: "cli-acp-jetbrains.md",
    url: "https://docs.devin.ai/cli/acp/jetbrains.md",
    why: "`devin acp` driven by JetBrains AI Chat — second client, same wire.",
  },
  {
    file: "cli-acp-xcode.md",
    url: "https://docs.devin.ai/cli/acp/xcode.md",
    why: "`devin acp` driven by Xcode — third client; also the MCP bridge story.",
  },
  {
    file: "cli-reference-commands.md",
    url: "https://docs.devin.ai/cli/reference/commands.md",
    why: "Devin CLI command and flag reference, including the `devin acp` entry we spawn and its global flags.",
  },
  {
    file: "cli-changelog-stable.md",
    url: "https://docs.devin.ai/cli/changelog/stable.md",
    why: "Devin CLI release notes. The wire-drift watch: ACP-surface changes land here before they break us.",
  },
]

const OUT_DIR = join(import.meta.dir, "..", "docs", "acp")

const header = (page: Page, fetchedOn: string): string =>
  [
    "<!--",
    `  source: ${page.url}`,
    `  fetched: ${fetchedOn}`,
    "  generated by: scripts/fetch-devin-acp-docs.ts",
    `  why: ${page.why}`,
    "  Do not edit by hand. Re-run the script; hand edits are overwritten.",
    "-->",
    "",
  ].join("\n")

const main = async (): Promise<number> => {
  const check = process.argv.includes("--check")
  await mkdir(OUT_DIR, { recursive: true })
  const fetchedOn = new Date().toISOString().slice(0, 10)
  const drifted: string[] = []

  for (const page of PAGES) {
    const response = await fetch(page.url)
    if (!response.ok) {
      console.error(`FAIL ${page.file}: ${response.status} ${page.url}`)
      return 1
    }
    const body = (await response.text()).trimEnd()
    const target = join(OUT_DIR, page.file)
    const next = header(page, fetchedOn) + body + "\n"

    const previous = await Bun.file(target).text().catch(() => "")
    // Compare bodies only: a refetch on a different day must not read as drift.
    const previousBody = previous.slice(previous.indexOf("-->") + 3).trim()
    if (previousBody !== body.trim()) drifted.push(page.file)

    if (check) {
      console.log(`${drifted.includes(page.file) ? "DRIFT" : "  ok "} ${page.file} (${body.length} B)`)
    } else {
      await Bun.write(target, next)
      console.log(`wrote ${page.file} (${next.length} B)`)
    }
  }

  if (check && drifted.length > 0) {
    console.error(`\n${drifted.length} page(s) drifted: ${drifted.join(", ")}`)
    console.error("Re-run without --check to refresh, then re-verify the wire inventory in .planning/.")
    return 1
  }
  return 0
}

process.exit(await main())